# Nome do projeto (apenas letras minúsculas e underscores)
name: 'dbt_dgasparsysmap'
version: '1.0.0'
config-version: 2

# Perfil usado pelo projeto
profile: 'default'

# Configuração dos caminhos para os diferentes tipos de arquivos
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Diretório para armazenar arquivos SQL compilados
target-path: "target"

# Diretórios a serem removidos pelo comando `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuração dos modelos
models:
  dbt_dgasparsysmap:
    # A configuração abaixo mapeia a pasta 'raw' para o esquema 'raw'
    raw:
      +schema: raw
      +materialized: table
    stg:
      +schema: stg
      +materialized: table
    refined:
      +schema: refined
      +materialized: table