version: 2

sources:
  - name: case_sysmap
    database: case-sysmap
    schema: dbt_dgasparsysmap_raw
    tables:
      - name: triggo_shop
        description: "Tabela de dados brutos de clientes e pedidos, carregada via dbt seed."
        columns:
          - name: id
            description: "ID único para cada registro."
            tests:
              - unique
              - not_null