version: 2

models:
  - name: customer_orders_summary
    description: "A view that combines customer information with their order history, including first and most recent order dates, and total number of orders."
    config:
      materialized: view
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: first_name
        description: "Customer's first name"
      - name: last_name
        description: "Customer's last name"
      - name: first_order_date
        description: "Date of the customer's first order"
      - name: most_recent_order_date
        description: "Date of the customer's most recent order"
      - name: number_of_orders
        description: "Total number of orders placed by the customer"

sources:
  - name: case-sysmap
    database: case-sysmap
    schema: stg_market
    tables:
      - name: customers
        description: "Raw customer data"
        columns:
          - name: id
            description: "Unique customer identifier"
          - name: first_name
            description: "Customer's first name"
          - name: last_name
            description: "Customer's last name"
      - name: orders
        description: "Raw order data"
        columns:
          - name: id
            description: "Unique order identifier"
          - name: user_id
            description: "Customer identifier for the order"
          - name: order_date
            description: "Date the order was placed"
          - name: status
            description: "Current status of the order"